### PR TITLE
add back 0..4 testing

### PR DESCRIPTION
**Pull request by tkelman**
if you don't support 0.4 any more, you need to update REQUIRE accordingly

### CODE REVIEW

**Comment by tkelman** [comment]
If this isn't going to work, then you need to modify the julia requirement of the tag on metadata, otherwise the package will break for all users on 0.4 if they Pkg.update.

**Comment by spencerlyon2** [comment]
Tests fail on 0.4 only because type inference isn't able to infer the return value of one of my functions. The code itself runs -- it will just introduce type instabilities for 0.4 and not on 0.5+.

**Comment by tkelman** [comment]
in that case, should only use inferred on 0.5.

**Comment by spencerlyon2** [comment]
Done

**Pull request merged**
