### PR TITLE
Starting new documentation

### PR DESCRIPTION
**Pull request by stephenbnicar**
In reference to [#136](https://github.com/QuantEcon/QuantEcon.jl/issues/136).

I've made a stab at starting to update the documentation using `Documenter.jl`.  I'm
a bit of a newbie to Julia, but I used `Documenter.jl` to document a simple [package](https://github.com/stephenbnicar/BeaData.jl) I wrote and I feel like I'm getting the hang of it.

I thought a good place to start would be to just reformat the existing documentation using `Documenter.jl`, so that's what I've done here.  I have not edited any of the existing docstrings or added any of the features of `DocStringExtensions.jl`.

The actual html pages with the new layout can be found in the `docs/build` folder.

A description of the changes I made follows: comments, questions and feedback are welcome.
- New `docs` folder, replacing the old one, using structure and files needed by `Documenter.jl`
- The initial new site layout mostly mirrors the old one:
  - **Home**: Taken from current documentation and edited to remove/fix broken links
    and remove references to QuantEcon.Models module which is not present in current
    version of QuantEcon
  - **API/QuantEcon**: docstrings from QuantEcon.jl organized by Exported and Internal
  - **Contributing**: taken from quant-econ.org site
  - no user guide yet, but a new page can be added easily when written
- Included commented-out code in `make.jl` for deploying the docs (see [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#The-deploydocs-Function-1)).  For auto-deployment of the docs, someone with the appropriate permissions would need to generate SSH Deploy Keys that will allow Travis to push changes to the repository (see [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#Deploy-Keys-1)).
- Updated `travis.yml` file to allow for auto-deployment of docs after each new commit
  to the master branch (commented out)
- Added `docs/build` to `.gitignore`: the default setup is to push auto-generated docs
  to a `gh-pages` branch, so the `master` branch should not contain these files (see [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#.gitignore-1)).

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Thank you very much for working on this! I will try to review and merge within the next day or two

**Comment by jstac** [comment]
@stephenbnicar Thanks, much appreciated.

**Comment by sglyon** [comment]
I'm really sorry this sat for so long. Somehow it slipped through my radar after I initially saw it.

I am going to merge right now and make a couple minor adjustments.

**Comment by stephenbnicar** [comment]
No problem.  Glad to help.

**Pull request merged**
