### PR TITLE
Move the models

### PR DESCRIPTION
**Pull request by spencerlyon2**

### CODE REVIEW

**Comment by spencerlyon2** [comment]
@mmcky this is good to go whenever you have the website prepared

**Comment by mmcky** [comment]
@spencerlyon2 Thanks!. 
I think we will also need to update the ``QuantEcon.jl/solutions`` notebooks. 

On the python side - we have one challenge regarding imports for the ``solutions`` notebooks. Have a suggestion on how to make this work well.

https://github.com/QuantEcon/QuantEcon.py/pull/206

**Comment by spencerlyon2** [comment]
@mmcky Updated solutions

**Comment by mmcky** [comment]
@spencerlyon2 Much of this migration work has now been done and is sitting in the ``migrate-applications`` branch of ``quant-econ-private`` repo. I have taken the ``examples/`` and ``solutions/`` data and integrated them into each relevant topic.

Solutions notebooks have been differentiated with ``_py`` and ``_jl`` postpends.

**Comment by spencerlyon2** [comment]
OK great, what else needs to be done on the Julia side then?

// Spencer

**Comment by mmcky** [comment]
I copied ``examples`` and ``solutions`` in the ``sl/move-models`` branch to ``QuantEcon.applications`` and organised by ``topic``. The residuals (if any) are contained in ``QuantEcon.applications\_archive_\jl\``. 

Therefore it should just be a matter of deleting ``examples/`` and ``solutions``. But I am still running the diffs to verify all the files have been linked back up appropriately.

**Comment by spencerlyon2** [comment]
OK great. When you have finished that let me know and we'll press the
delete button over here

// Spencer

**Comment by spencerlyon2** [comment]
Hey @mmcky I just overwrote this PR to completely remove any notion of models, solutions, or examples. 

This should be the right way to work with QuantEcon.applications#7.

If anything here looks wrong, let me know.

Tests pass locally, we'll see what travis says.

**Comment by mmcky** [comment]
@sglyon My suggestion re: PR's to remove the ``examples`` and ``models```. Let's accept these in 2 days time on both ``QuantEcon.jl`` and ``QuantEcon.py``. This way if we find some errors in the site - it is possible to revert the html really easily if these repo's haven't changed yet. Once the ``html`` code is in production for the week we can then accept these PRs

**Pull request merged**
