### PR TITLE
Add docs 

### PR DESCRIPTION
**Pull request by ranjanan**
This PR is meant to add docs. There's more coming.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Thanks for working on this. 

A much needed addition. 

This might give me the motivation to actually update the API docs on the website :)

I'll leave this open as you add more docs, please let me know when you would like this to be merged.

**Comment by ranjanan** [comment]
Thanks Spencer! This PR covers some documentation, but there are still a few more exported types/functions without docs. 
- [ ] Communication_classes
- [ ] LSS
- [ ] Kalman
- [ ] set_state!
- [ ] meshgrid
- [ ] gridmake
- [ ] gridmake!
- [ ] ckron
- [ ] VFI
- [ ] PFI
- [ ] MPFI
- [ ] evaluate_policy!
- [ ] compute_greedy

I'll keep plugging away at this, but could you point to me to a docs source for `Kalman`, `LSS`, `set_state!`? Also, could you help with writing docs for some of the util functions? I don't think their equivalents are present in the python package.

**Comment by spencerlyon2** [comment]
Hey @ranjanan we need to extend the Julia Kalman code to match the python version.

They were the same until about 6 months ago (I think) the Python version became more general and we haven't updated the Julia side yet. Once we've made the changes we should be able to document `Kalman` and `set_state!`.

[Here](https://github.com/QuantEcon/QuantEcon.py/blob/4eade8da026435a4fd3b61b3ffbabac51a61bcfc/quantecon/markov/ddp.py#L538-L555) are the python docstrings for `compute_greedy`

I can write up some docstrings for the routines in util.

**Comment by spencerlyon2** [comment]
Also we should delete the export of  `evaluate_policy!`

I believe that was left over from when we had the models in the package rather than in a separate repo

**Comment by ranjanan** [comment]
Alright, I'll send a separate PR to delete `evaluate_policy!`. 
We can get to `Kalman` once the implementation is finished, I guess. 
`compute_greedy` is done now.

**Comment by spencerlyon2** [comment]
@ranjanan thanks again for the help here.

I'll merge this, and open issues to add docs and rework kalman.

**Comment by ranjanan** [comment]
Cool, thanks! :+1:

**Pull request merged**
