### PR TITLE
Compat bump

### PR DESCRIPTION
**Pull request by jlperla**
@oyamad  I am just bumping compat here and running the tests.  When I run them locally I get a few warnings:
```
* test_markov_approx.jl
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: Failed to match first 4 moments.  Just matching 2.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:407
┌ Warning: The quadrature method may perform poorly for highly persistent processes.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:440
┌ Warning: Failed to match first 2 moments. Just matching 1.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:389
┌ Warning: Failed to match first 2 moments. Just matching 1.
└ @ QuantEcon C:\Users\jesse\Documents\GitHub\QuantEcon.jl\src\markov\markov_approx.jl:389
```

But not sure if that is what it used to do, as it isn't triggering the unit tests to fail.  Is this a regression or something innocuous I can still merge over.

### CODE REVIEW

**Comment by jlperla** [comment]
@oyamad I am not sure if the warnings on the `test_markov_approx.jl` are serious but I dug into it a little more.
- With this PR the issues are happening with both 1.6 and 1.10, so I don't think it is a julia version thing.
- I also reran the unit tests on the code prior to this PR and am getting the same issues.

So my hunch is that these problems have nothing to do with this PR and I wonder if we should just merge and tag a release?

**Comment by Shunsuke-Hori** [comment]
@jlperla Let me chime in as I wrote that test. In short, the warning is an expected behavior. I just replicated the exercises the original paper has done, which include a case of approximating highly persistent processes where the method fails to match higher-order moments and can get limited accuracy.

**Comment by jlperla** [comment]
Great, thanks. So thoughts on merging and tagging this? I don't want to do that unilaterally

**Comment by jlperla** [comment]
This PR would also implement #289 and #290

**Comment by Shunsuke-Hori** [comment]
@jlperla I don't see any issue with merging this. Thank you!!

**Pull request merged**
